_muzzles = [
	["muzzle_snds_338_black","Sound Suppressor (.338, Black)"],
	["muzzle_snds_338_green","Sound Suppressor (.338, Green)"],
	["muzzle_snds_338_sand","Sound Suppressor (.338, Sand)"],
	["muzzle_snds_570","Sound Suppressor (5.7 mm)"],
	["muzzle_snds_58_blk_F","Stealth Sound Suppressor (5.8 mm, Black)"],
	["muzzle_snds_58_ghex_F","Stealth Sound Suppressor (5.8 mm, Green Hex)"],
	["muzzle_snds_58_hex_F","Stealth Sound Suppressor (5.8 mm, Hex)"],
	["muzzle_snds_58_wdm_F","Stealth Sound Suppressor (5.8 mm, Green)"],
	["muzzle_snds_65_TI_blk_F","Stealth Sound Suppressor (6.5 mm, Black)"],
	["muzzle_snds_65_TI_ghex_F","Stealth Sound Suppressor (6.5 mm, Green Hex)"],
	["muzzle_snds_65_TI_hex_F","Stealth Sound Suppressor (6.5 mm, Hex)"],
	["muzzle_snds_93mmg_tan","Sound Suppressor (9.3mm, Tan)"],
	["muzzle_snds_93mmg","Sound Suppressor (9.3mm, Black)"],
	["muzzle_snds_acp","Sound Suppressor (.45 ACP)"],
	["muzzle_snds_B_arid_F","Sound Suppressor (7.62 mm, Arid)"],
	["muzzle_snds_B_khk_F","Sound Suppressor (7.62 mm, Khaki)"],
	["muzzle_snds_B_lush_F","Sound Suppressor (7.62 mm, Lush)"],
	["muzzle_snds_B_snd_F","Sound Suppressor (7.62 mm, Sand)"],
	["muzzle_snds_B","Sound Suppressor (7.62 mm)"],
	["muzzle_snds_H_khk_F","Sound Suppressor (6.5 mm, Khaki)"],
	["muzzle_snds_H_MG_blk_F","Sound Suppressor LMG (6.5 mm, Black)"],
	["muzzle_snds_H_MG_khk_F","Sound Suppressor LMG (6.5 mm, Khaki)"],
	["muzzle_snds_H_MG","Sound Suppressor LMG (6.5 mm)"],
	["muzzle_snds_H_snd_F","Sound Suppressor (6.5 mm, Sand)"],
	["muzzle_snds_H_SW","Sound Suppressor LMG (6.5 mm)"],
	["muzzle_snds_H","Sound Suppressor (6.5 mm)"],
	["muzzle_snds_L","Sound Suppressor (9 mm)"],
	["muzzle_snds_m_khk_F","Sound Suppressor (5.56 mm, Khaki)"],
	["muzzle_snds_m_snd_F","Sound Suppressor (5.56 mm, Sand)"],
	["muzzle_snds_M","Sound Suppressor (5.56 mm)"],
	["muzzle_tma_65","SIMCOM Adapter (6.5 mm)"]
];
_muzzles;